### ISSUE TITLE
The GPU utilization is low

### ISSUE THREAD

**Issue by WANGBohaO-jpg** [yihong-chen/neural-collaborative-filtering#21]
When I run the code on RTX4090, the utilization of the GPU is always 0%, and I don't change the code. Is it alright?

**Comment by yihong-chen** [comment]
@WANGBohaO-jpg Did you manage to get it run in the end? I haven't run the code for quite a while though I suspect it might be due to the version of pytorch you are using.

**Comment by yihong-chen** [comment]
closed due to inactivity.
