### ISSUE TITLE
The code implementation does not match the original paper

### ISSUE THREAD

**Issue by WANGBohaO-jpg** [yihong-chen/neural-collaborative-filtering#22]
The function _sample_negative in data.py appears to be incorrect. It currently utilizes ratings to generate negative samples, resulting in the exclusion of test items for each user from the negative samples. But the test items should be treated as negative samples in training set.

**Comment by yihong-chen** [comment]
@WANGBohaO-jpg Thanks for pointing out this. Would you like to create a pull request to fix the issue?

**Comment by patelrajnath** [comment]
@yihong-chen I created a full request fixing the above.  Have a look.

**Comment by yihong-chen** [comment]
This is solved by Raj's contribution. See pull request #23 for more details.

**Comment by yihong-chen** [comment]
Closed as complete.
