### ISSUE TITLE
Test Dataloader for large dataset.

### ISSUE THREAD

**Issue by RuihongQiu** [yihong-chen/neural-collaborative-filtering#7]
Maybe a test dataloader for iterate the test set is more user friendly for large dataset? Just simply treat all test data as a huge batch sometimes will cause OOM error.

![image](https://user-images.githubusercontent.com/17882988/54879003-eddce280-4e7f-11e9-8624-73a5ad57b37d.png)

 Sometimes the size could be like this.

**Comment by LaceyChen17** [comment]
Couldn't agree more. A test dataloader would be better. I will add it to my todo list.

**Comment by RuihongQiu** [comment]
Hope to see the method. I try to implement it but get stuck in the calculation of HR and NDCG.

**Comment by yihong-chen** [comment]
> Hi Yihong, I created a PR for this issue. Have a look. 

Looks awesome to me. Merged:)
